CREATE DATABASE IF NOT EXISTS bib
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE bib;

CREATE TABLE IF NOT EXISTS belegung (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bib VARCHAR(50) NOT NULL,
    percentage INT NOT NULL,
    occupied INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX (bib, created_at)
);
